api_version = "2023-07"

[[extensions]]
type = "ui_extension"
name = "clippify-checkout-ui"
handle = "clippify-checkout-ui"

[[extensions.targeting]]
module = "./src/Checkout.tsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
api_access = true
network_access = true

